run:
  go: '1.22.6'

linters:
  enable:
    - goimports
    - bodyclose
    - whitespace
  disable:
    errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/AndIsaev/go-musthave-diploma-tlp

