version: '3'

services:

  database:
    container_name: postgres
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_DB=localDB
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-database:/var/lib/postgresql/data

volumes:
  postgres-database: